name: build
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Dart
        uses: cedx/setup-dart@master
        with:
          architecture: x64
          release-channel: stable
          version: latest
      - name: Check environment
        run: |
          dart --version
          pub --version
      - name: Fetch sources
        uses: actions/checkout@master
      - name: Install dependencies
        run: pub get
      - name: Run tests
        run: pub run build_runner test
