name: main
on: push
jobs:
  test:
    runs-on: ${{matrix.platform}}
    strategy:
      matrix:
        platform: [macos-latest, ubuntu-latest, windows-latest]
    steps:
      - name: Fetch sources
        uses: actions/checkout@v3
      - name: Set up Dart
        uses: cedx/setup-dart@v3
        with:
          architecture: x64
          release-channel: stable
          version: latest
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: |
          dart test --coverage=var
          dart run coverage:format_coverage --in=var/test --lcov --out=lcov.info --packages=.dart_tool/package_config.json --report-on=lib
      - name: Collect code coverage
        if: success()
        uses: coverallsapp/github-action@master
        with:
          flag-name: ${{matrix.platform}}
          github-token: ${{secrets.GITHUB_TOKEN}}
          path-to-lcov: lcov.info
          parallel: true
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Upload code coverage
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          parallel-finished: true
