name: Setup Dart Action
description: Set up your GitHub Actions workflow with a specific version of the Dart SDK.
author: Cédric Belin

branding:
  color: blue
  icon: download

inputs:
  architecture:
    description: The processor architecture of the Dart SDK ("x64", "ia32", "arm64" or "arm").
    required: false
  release-channel:
    description: The release channel of the Dart SDK ("stable", "beta", "dev" or "main").
    default: stable
    required: false
  version:
    description: The version of the Dart SDK.
    default: latest
    required: false

runs:
  using: node16
  main: bin/setup_dart.mjs
