name: setup-dart
description: Set up your GitHub Actions workflow with a specific version of the Dart SDK.
author: Cédric Belin <cedric@belin.io>

branding:
  color: blue
  icon: package

inputs:
  architecture:
    description: The architecture of the Dart SDK ("arm", "arm64", "ia32" or "x64").
    default: x64
    required: false
  release-channel:
    description: The release channel of the Dart SDK ("dev" or "stable").
    default: stable
    required: false
  version:
    description: The version of the Dart SDK.
    default: latest
    required: false

runs:
  using: node12
  main: bin/setup_dart.js
