site_name: Setup Dart Action
site_description: Set up your GitHub Actions workflow with a specific version of the Dart SDK.
site_author: Cédric Belin - cedric@belin.io
site_url: https://dev.belin.io/setup-dart

docs_dir: .
site_dir: ../www

repo_name: GitHub
repo_url: https://github.com/cedx/setup-dart
edit_uri: ''

copyright: Copyright &copy; 2020 Cédric Belin
google_analytics:
  - !!python/object/apply:os.getenv [GOOGLE_ANALYTICS_ID]
  - auto

extra:
  social:
    - {type: globe, link: 'https://belin.io'}
    - {type: github, link: 'https://github.com/cedx'}
    - {type: twitter, link: 'https://twitter.com/cedxbelin'}
    - {type: linkedin, link: 'https://linkedin.com/in/cedxbelin'}

markdown_extensions:
  - admonition
  - codehilite
  - meta

nav:
  - Overview: index.md
  - Usage: usage.md
  - About:
      - Changelog: about/changelog.md
      - License: about/license.md
      - See also: about/see_also.md

theme:
  name: material
  favicon: img/favicon.ico
  palette: {primary: yellow, accent: yellow}
