name: build
on:
  - pull_request
  - push
jobs:
  test:
    runs-on: windows-latest
    steps:
      - name: Fetch sources
        uses: actions/checkout@v2
      - name: Set up Lix
        uses: lix-pm/setup-lix@master
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: |
          lix download
          npm install
      - name: Run tests
        run: haxe test.hxml
      - name: Collect code coverage
        env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: success()
        run: npm run coverage
